### PR TITLE
fix typo in docs

### PR DESCRIPTION
**Pull request by ThePerfectComputer**
I'm working my way through the Bluespec docs to improve my understanding of Bluespec, and also converting them to HTML. More fixes to come hopefully.

### CODE REVIEW

**Comment by ThePerfectComputer** [comment]
rôle is French for role(I speak French) but I assume that the document was meant to be written in English?

**Comment by quark17** [comment]
Thanks!  FYI, we have been looking into converting the documents away from LaTeX and into reStructuredText format, which would allow us to generate HTML versions, and they could automatically be available on the ReadTheDocs website.

As for the word rôle, that's technically an acceptable spelling in English, and might even be the "proper" spelling in the UK.  To my modern American eyes, it doesn't look wrong, but it feels a bit antiquated or haughty.  Assuming that the documentation uses American spellings elsewhere (eg "initialize"), it probably makes sense to change this.  But I can check with the original author.

**Comment by ThePerfectComputer** [comment]
Oh? Where are the readthedocs? I've just been using pandoc to convert to HTML without much hassle. I'd be more than happy to rewrite things as RST if that would help...

**Comment by ThePerfectComputer** [comment]
Oh - I think I read your message wrong, it sounds like you don't have a read the docs yet

**Comment by ThePerfectComputer** [comment]
When are you targeting having readthedocs up and running because I imagine I'll have learnbsc.dev  or bluespec.dev up and running by the end of next week...

**Comment by quark17** [comment]
Hosting on ReadTheDocs is easy, and I'm happy to do that, once we have something to host.  The first step is just converting the content to reStructuredText format.  If you've got the energy to work on documentation, would you be willing to put it towards creating RST files?  @rsnikhil has started writing RST documents for other projects, and has looked into how we might express the BSC documentation -- for example, the BSV Ref Guide has grammar blocks, that differ from how RST natively displays grammar, and so there was a question of how best to express that in RST.  I don't know how far he's gotten, but I anticipate that it has to wait behind many higher-priority projects.  But I'm sure that help with producing the RST files would be appreciated, if you've got energy to put towards documentation.

One aspect, though, is that he wants to try to unify the structure (and sources) for the BSV and BH guides, where possible.  But I'm sure that can be done incrementally, after it's in RST.

**Comment by ThePerfectComputer** [comment]
Yeah - I've got some energy. I can at least start with the BH docs, since I plan to read those anyways - as I reference the BH grammar for a potential BH plugin in the future.

**Comment by ThePerfectComputer** [comment]
I'll see how far I've gotten with RST translation by next week then.

**Comment by ThePerfectComputer** [comment]
I'm not sure that RST has any special treatments for grammar, which may mean that it just gets treated as text...

I hope this isn't an issue - it would certainly still be readable and all.

**Comment by ThePerfectComputer** [comment]
I'm going to close this pull request and focus on converting to RST.

**Comment by ThePerfectComputer** [comment]
Closing.

**Comment by rsnikhil** [comment]
Re. "I'm not sure that RST has any special treatments for grammar, which may mean that it just gets treated as text..."

Please see: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#grammar-production-displays

Pro: automatic cross-referencing (hyperlinking) of non-terminals from uses to definitions

Cons:

* Not-very pretty rendering (IMHO): fixed-width font, using double
    quotes etc. for both non-terminals and terimnals, instead of using
    different fonts for that.

* Does not allow more than one production with the same non-terminal
    left-hand-side.  We often do this to split a production with many
    right-hand-sides, grouping things according to the explanatory text.

**Comment by quark17** [comment]
FYI, issue #377 is a request for web-based/HTML/accessible documentation.  Feel free to continue any discussion there.

**Pull request closed without merging**
